os: linux
dist: bionic

language: shell

env:
  global:
    - DOCKER_REPO=carlosedp/arm_exporter
    - ARCHS="linux/arm/v6,linux/arm/v7,linux/arm64"

before_install:
    - set -e
    - curl -fsSL https://get.docker.com | sh
    - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - mkdir -vp ~/.docker/cli-plugins/
    - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.darwin-amd64" > ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - sudo systemctl start docker

script: bash -c ./ci.sh
